### PR TITLE
Review hello world tutorial 3

### PR DESCRIPTION
**Pull request by lucafavatellawork**

### CODE REVIEW

**Comment by lucafavatellawork** [comment]
@miklosduma As the test uses test data from the network rather than the filesystem I am not sure how to propose PR for this change without breaking CI in master or PR. Guidance welcome.

**Comment by miklosduma** [comment]
> @miklosduma As the test uses test data from the network rather than the filesystem I am not sure how to propose PR for this change without breaking CI in master or PR. Guidance welcome.

As a matter of fact I'm really surprised this request gets called at all. Not having an incoming field looks outright weird to me. Confirming with @jacobythwaites if this is expected behaviour at all.

If you don't care about the value of a field you still use a FLAG field to call an operation and tell the sequencer when and how to call that operation.

**Comment by lucafavatellawork** [comment]
> As for proposing the changes - I know it's not optimal - but we might do a 2 step merge/change, first importing the SSE configuration locally and replacing the local ref with a URL after the merge.

@miklosduma Could you please have a second look at this? I will open the second PR reverting the source to HTTP once this merged.

**Comment by miklosduma** [comment]
@lucafavatellawork if we want to go with the no-field request I guess it would deserve a line or some explanation that it is a possibility - perhaps with a disclaimer. Jacoby said that "The sequencing graph would get larger rapidly if you have lots of request-replies like that… probably best avoided."

Thing is, the order in which request/replies are called is not deterministic. I.e. the number of possible execution patterns increases exponentially.

**Comment by lucafavatellawork** [comment]
From past conversation I had the impression that the execution paths were computed at mix loading phase (i.e. once) - not at each call. Copying old conversation below for reference, I need to look better into this.

----

> @lucafavatellawork if we want to go with the no-field request I guess it would deserve a line or some explanation that it is a possibility - perhaps with a disclaimer. Jacoby said that "The sequencing graph would get larger rapidly if you have lots of request-replies like that… probably best avoided."
> 
> Thing is, the order in which request/replies are called is not deterministic. I.e. the number of possible execution patterns increases exponentially.

From [old code review comment](https://github.com/opensparkl/sse_cli/pull/56#discussion_r392335882):
> Q1. Can user put a mix with multiple requests with (1) same request fields, (2) same reply name and (3) same reply fields?
>
> ...
>
> Q4. Can user put a mix with multiple requests that have same request fields? In this case, could the backend determine to call a request though realize it does not lead to reply needed for response hence backtrack and attempt distinct request? Could side effects have happened that cannot be rolled back?
>
> Q5. Can a user put a mix with multiple requests, with same reply name and same reply fields? Dually to Q4: what about backtracking and side effects?

and from [subsequent comment](https://github.com/opensparkl/sse_cli/pull/56#discussion_r392361071):
> ...
>
> - A request will only be invoked if the fields sent by its reply contribute to the response (or another transaction goal such as a consume operation). If there are two or more requests, each of which can contribute to the same goal, only one of them will be called. I think it is random which one. So there will be no need to rollback. When the mix is written, the possible execution paths are calculated. At execution time, one of the paths will be picked. I.e. no rollback needed :)
> - See above, only one of the requests will be actually used at a time :)
>
> ...

**Comment by miklosduma** [comment]
I see 3 ways to approach this particular configuration (GetState):
- Leave it as it is. Yes, the operation does not use the field but since the field already exists and has date I see no harm in it. The field makes it explicit when/how the operation should be invoked
- Introduce another FLAG field to express the flow (field value is not actually needed)
- Leave out the input field like you suggested. My problem with this one is, that it would introduce an edge case into a basic tutorial requiring quite a bit of explanations and caveats

**Pull request closed without merging**
